# Generated by Django 4.0.4 on 2022-05-20 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('a_paterno', models.CharField(max_length=45, null=True)),
                ('a_materno', models.CharField(max_length=45, null=True)),
                ('fec_nacimiento', models.DateField(null=True)),
                ('numero', models.IntegerField()),
            ],
        ),
    ]
